package com.warehouse.model;

import com.warehouse.model.enums.ReorderPriority;

/**
 * Represents a smart stock reorder recommendation generated by the system.
 * Demonstrates CSE2006 Unit 2: Encapsulation & Domain Modeling.
 */
public class ReorderRecommendation {
    private Long productId;
    private String productName;
    private String sku;
    private int currentStock;
    private int averageDailyDemand;
    private int supplierLeadTime;
    private int safetyStock;
    private int reorderPoint;
    private int recommendedQuantity;
    private ReorderPriority priority;
    private String recommendationReason;

    public ReorderRecommendation(Long productId, String productName, String sku, int currentStock,
                                 int averageDailyDemand, int supplierLeadTime, int safetyStock,
                                 int reorderPoint, int recommendedQuantity, ReorderPriority priority,
                                 String recommendationReason) {
        this.productId = productId;
        this.productName = productName;
        this.sku = sku;
        this.currentStock = currentStock;
        this.averageDailyDemand = averageDailyDemand;
        this.supplierLeadTime = supplierLeadTime;
        this.safetyStock = safetyStock;
        this.reorderPoint = reorderPoint;
        this.recommendedQuantity = recommendedQuantity;
        this.priority = priority;
        this.recommendationReason = recommendationReason;
    }

    public Long getProductId() {
        return productId;
    }

    public String getProductName() {
        return productName;
    }

    public String getSku() {
        return sku;
    }

    public int getCurrentStock() {
        return currentStock;
    }

    public int getAverageDailyDemand() {
        return averageDailyDemand;
    }

    public int getSupplierLeadTime() {
        return supplierLeadTime;
    }

    public int getSafetyStock() {
        return safetyStock;
    }

    public int getReorderPoint() {
        return reorderPoint;
    }

    public int getRecommendedQuantity() {
        return recommendedQuantity;
    }

    public ReorderPriority getPriority() {
        return priority;
    }

    public String getRecommendationReason() {
        return recommendationReason;
    }

    @Override
    public String toString() {
        return String.format("""
                ------------------------------------------
                REORDER RECOMMENDATION
                ------------------------------------------
                Product: %s (SKU: %s) [ID: %d]
                Current Stock: %d
                Average Daily Demand: %d units/day
                Supplier Lead Time: %d days
                Safety Stock: %d
                Reorder Point: %d
                Recommended Quantity: %d
                Priority: %s
                Reason: %s
                ------------------------------------------""",
                productName, sku, productId, currentStock, averageDailyDemand,
                supplierLeadTime, safetyStock, reorderPoint, recommendedQuantity, priority, recommendationReason);
    }
}
